# https://docs.asciidoctor.org/asciidoc/latest/sections/auto-ids/
# Convert internal links use correct xref format for autogenerated IDs

# all, link, angled, hyphen
fix_type =  ARGV[0].downcase

# convert block images to inline images
# block images hand issues previously
if fix_type == "all" || fix_type == "inline"
  puts "Converting block images to inline images"

  files_with_block_image = %x[ grep -rlE --include \\*.adoc "image::" ]

  files_with_block_image.split.uniq.each do |file|
    %x[ sed -i "s|image::|image:|g" #{file} ]
  end
  puts "Done"
end

# convert block images to inline images
# block images hand issues previously
if fix_type == "all" || fix_type == "prefix"
  puts "Removing /img/ from image paths"

  files_with_block_image = %x[ grep -rlE --include \\*.adoc "image(:|::)/img/" ]

  files_with_block_image.split.uniq.each do |file|
    %x[ sed -i "s|image::/img/|image::|g" #{file} ]
    %x[ sed -i "s|image:/img/|image:|g" #{file} ]
  end
  puts "Done"
end

