# https://docs.asciidoctor.org/asciidoc/latest/sections/auto-ids/
# Convert internal xrefs to use correct format for autogenerated IDs
# E.g. <<some-section-header, Some Section Header>> becomes <<_some_secton_header, Some Section Header>>

files_with_link = %x[ grep -rl --include \\*.adoc "<<" ]

files_with_link.split.uniq.each do |file|
  internal_links_in_file = %x[ grep -oE "<<([^,-]*-*)*" #{file} ]
  internal_links_in_file.split.uniq.each do |link|
    new_link = link.gsub('-','_')
    if !new_link.start_with?("<<_")
      new_link = new_link.sub('<<','<<_')
    end
    %x[ sed -i "s|#{link}|#{new_link}|g" #{file} ]
  end
end
