# https://docs.asciidoctor.org/asciidoc/latest/sections/auto-ids/
# Convert internal xrefs to use correct format for autogenerated IDs
# E.g. <<some-section-header, Some Section Header>> becomes <<_some_secton_header, Some Section Header>>

files_with_link = %x[ grep -rl --include \\*.adoc "<<" ]

files_with_link.split.uniq.each do |file|
    internal_links_in_file = %x[ grep -oE "<<([a-z0-9]*-*[a-z0-9]*)*[^,]" #{file} ]
    internal_links_in_file.split.uniq.each do |link| 
        %x[ sed -i "s|#{link}|#{link.sub('<<','<<_').gsub('-','_')}|g" #{file} ]
    end
end
